root: true
parser: '@typescript-eslint/parser'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - prettier

plugins:
  - '@typescript-eslint'

ignorePatterns: ['*.cjs']

overrides:
  - files: ['*.svelte']
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'

  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'

  no-self-assign: off

  '@typescript-eslint/no-non-null-assertion': off

parserOptions:
  sourceType: 'module'
  ecmaVersion: 2020
  extraFileExtensions: [.svelte]

env:
  browser: true
  es2017: true
  node: true
