services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/local/src/pet-monitor-app
    depends_on:
      - rocket

  rocket:
    build: ./pet-monitor-app
    ports:
      - 8000:8001
    environment:
      - PASSWORD=123
