services:
  proxy:
    build:
      context: ./client
      dockerfile: production.Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rocket

  rocket:
    build:
      context: ./pet-monitor-app
      dockerfile: production.Dockerfile
    ports:
      - 8001:8001
    volumes:
      - /var/local/lib/pet-monitor-app/
    environment:
      PASSWORD: 123

# fmp4streamer:
#   build: ./fmp4streamer
#   ports:
#     - 8000:8000
#   volumes:
#     - /dev/video0:/dev/video0
#     - ./fmp4streamer/fmp4streamer.conf:/usr/local/src/fmp4streamer/fmp4streamer.conf
