[package]
name = "pet-monitor-app"
description = "Simple and secure pet monitor for Raspberry Pi"
license = "MIT"
repository = "https://github.com/Stonks3141/pet-monitor-app"
readme = "https://github.com/Stonks3141/pet-monitor-app#readme"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"

[dependencies]
rocket = { version="0.5.0-rc.2", features=["json"] }
jsonwebtoken = "8.1"
clap = "3.2"
include_dir = "0.7"
quick-error = "2.0"
confy = "0.4"
serde = "1.0"
serde_with = { version="2.0", features=["base64", "chrono_0_4"] }
chrono = "0.4"
ring = "0.16"
rust-argon2 = "1.0"
rscam = "0.5"
mse_fmp4 = "0.2"

[profile.release]
codegen-units = 1
lto = true