[package]
name = "pet-monitor-app"
description = "Simple and secure pet monitor for Raspberry Pi"
license = "MIT"
repository = "https://github.com/Stonks3141/pet-monitor-app"
readme = "https://github.com/Stonks3141/pet-monitor-app#readme"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"

[dependencies]
rocket = "0.5.0-rc.2"
async-std = "1.12"
jsonwebtoken = "8.1"
serde = "1.0"
ring = "0.16"
chrono = "0.4"
rust-argon2 = "1.0"
