[package]
name = "pet-monitor-app"
description = "Simple and secure pet monitor for Raspberry Pi"
license = "MIT"
repository = "https://github.com/Stonks3141/pet-monitor-app"
readme = "https://github.com/Stonks3141/pet-monitor-app#readme"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[dependencies]
rocket = "0.5.0-rc.2"
jsonwebtoken = "8.1"
ring = "0.16"
rust-argon2 = "1.0"
rscam = "0.5"
mse_fmp4 = "0.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true