[package]
name = "pet-monitor-app"
version = "0.1.0"
authors = ["Sam Nystrom <samuel.l.nystrom@gmail.com>"]
edition = "2021"
rust-version = "1.64"
description = "Simple and secure pet monitor for Raspberry Pi"
documentation = "https://github.com/Stonks3141/pet-monitor-app"
readme = "https://github.com/Stonks3141/pet-monitor-app#readme"
homepage = "https://github.com/Stonks3141/pet-monitor-app"
repository = "https://github.com/Stonks3141/pet-monitor-app"
license = "MIT"
keywords = ["cli", "video", "server", "streaming", "media"]
categories = ["command-line-utilities", "multimedia"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "tls"] }
jsonwebtoken = "8.1"
clap = "4.0"
log = "0.4"
simple_logger = "4.0"
include_dir = "0.7"
confy = "0.5"
parking_lot = "0.12"
serde = "1.0"
serde_with = { version = "2.0", features = ["base64", "chrono_0_4"] }
serde_repr = "0.1"
anyhow = "1.0"
chrono = "0.4"
ring = "0.16"
rust-argon2 = "1.0"
bitflags = "1.3"
fixed = "1.19"
rscam = "0.5"
x264 = { git = "https://github.com/Stonks3141/x264.git" }

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"
quickcheck = "1.0"
reqwest = { version = "0.11", features = ["cookies"] }

[[bin]]
name = "pet-monitor-app"
path = "src/main.rs"
