[package]
name = "pet-monitor-app"
version = "0.1.0"
authors = ["Sam Nystrom <samuel.l.nystrom@gmail.com>"]
edition = "2021"
rust-version = "1.63"
description = "Simple and secure pet monitor for Raspberry Pi"
documentation = "https://github.com/Stonks3141/pet-monitor-app"
readme = "https://github.com/Stonks3141/pet-monitor-app#readme"
homepage = "https://github.com/Stonks3141/pet-monitor-app"
repository = "https://github.com/Stonks3141/pet-monitor-app"
license = "MIT"
keywords = ["cli", "video", "server", "streaming", "media"]
categories = ["command-line-utilities", "multimedia"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "tls"] }
jsonwebtoken = "8.1"
clap = "4.0"
include_dir = "0.7"
confy = "0.5"
serde = "1.0"
serde_with = { version = "2.0", features = ["base64", "chrono_0_4"] }
anyhow = "1.0"
chrono = "0.4"
ring = "0.16"
rust-argon2 = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"
proptest = "1.0"

[profile.release]
codegen-units = 1
lto = true
strip = true

[[bin]]
name = "pet-monitor-app"
path = "src/main.rs"
