password_hash = '$argon2id$v=19$m=8192,t=3,p=4$q3iiSL2miJBqzrucyO+9Og$/L9Pg0ncrj+XbbZ1aGD4RajCOBMK0MsCnohMfeG6PHs'
jwt_secret = 'uMqJ0hbP1OBZwutJgs3FT2PGUcwJI/h6aCaa0wzGXkI='
jwt_timeout = 345600
domain = 'localhost'
host = '0.0.0.0'
port = 8080
resolution = [
    1280,
    720,
]
rotation = 0
framerate = 30
device = '/dev/video0'
