password_hash = '$argon2id$v=19$m=8192,t=3,p=4$BO1St77ggzWXbXcbFWNGCw$8eD2geYn0m9AIsqTYv5QheJuRIgTfc55RyHoexjygCQ'
jwt_secret = '7SriZgV8Hx43eFX26SGXVm5MTbjInhLa1e8LurotwzA='
jwt_timeout = 86400
domain = 'localhost'
resolution = [
    1280,
    720,
]
rotation = 0
framerate = 30
device = '/dev/video0'
