[package]
name = "v4l-streamer"
description = ""
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3", features = ["executor", "thread-pool"] }
rscam = "0.5"
# gstreamer = "0.18"
mse_fmp4 = "0.2"
