name: Build

on:
- push
- pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Rust
      run: |
        cargo build --verbose
        
    - name: Build React
      run: |
        cd client
        yarn add
        yarn build
      
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Rust tests
      run: |
        cargo test --verbose
        
    - name: Run React tests
      run: |
        cd client
        yarn add
        yarn run test
