name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: '-C debuginfo=0'

jobs:
  build-flake:
    name: Build Nix flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run build
        run: nix build
  
  Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run checks
        run: just check

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build tests
        run: just test --no-run
      - name: Run tests
        run: just test

  udeps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-udeps
        run: cargo +nightly install cargo-udeps
      - name: Find unused dependencies
        run: cargo +nightly udeps --all-targets

  Publish:
    needs:
      - Check
      - Test
      - udeps

    strategy:
      matrix:
        crate:
          - pet-monitor-app
          - mp4-stream
          - bmff

    uses: ./.github/workflows/publish.yml
    with:
      crate: ${{ matrix.crate }}
