name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run build
        run: nix build
  
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Run checks
        run: nix develop --profile check -c just check
      - name: Push to cachix
        run: cachix push stonks3141 check

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Run tests
        run: nix develop --profile check -c just test
      - name: Push to cachix
        run: cachix push stonks3141 check

  udeps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Find unused dependencies
        run: nix develop .#udeps --profile udeps -c cargo udeps --all-targets
      - name: Push to cachix
        run: cachix push stonks3141 udeps

  Publish:
    runs-on: ubuntu-latest
    environment: crates.io
    needs:
      - Build
      - Check
      - Test
      - udeps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Publish crates
        run: just publish ${{ secrets.CARGO_REGISTRY_TOKEN }}
