name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  Flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run build
        run: nix build
  
  Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: just check
        env:
          RUSTFLAGS: '-C debuginfo=0'

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Build tests
        run: cargo test --all-features --workspace --no-run
      - name: Run tests
        run: just test
        env:
          RUSTFLAGS: '-C debuginfo=0'

  udeps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - uses: dtolnay/rust-toolchain@nightly
      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-udeps
        run: cargo install cargo-udeps
      - name: Find unused dependencies
        run: cargo +nightly udeps --all-targets
        env:
          RUSTFLAGS: '-C debuginfo=0'
