name: Build

on:
- push
- pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Rust
      run: |
        cargo build
        cargo build -p v4l-streamer

    - name: Build React
      run: |
        yarn install --frozen-lockfile
        yarn build
      working-directory: ./client

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Rust tests
      run: |
        cargo test
        cargo test -p v4l-streamer

    - name: Run React tests
      run: |
        yarn install --immutable-cache
        yarn test
      working-directory: ./client

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Lint Rust
      run: |
        cargo clippy
        cargo clippy -p v4l-streamer

    - name: Lint React
      run: |
        yarn install --immutable-cache
        yarn lint
      working-directory: ./client
