name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install v4l2
        run: sudo apt-get install libv4l-0 libv4l-dev

      - name: Create dummy build directory
        working-directory: client
        run: mkdir build/

      - name: Build
        working-directory: pet-monitor-app
        run: cargo build

  Typescript-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: client
        run: yarn install --immutable --immutable-cache
      
      - name: Build
        working-directory: client
        run: yarn build

  Clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create dummy build directory
        working-directory: client
        run: mkdir build/

      - name: Run lints
        working-directory: pet-monitor-app
        run: cargo clippy

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: client
        run: yarn install --immutable --immutable-cache
      
      - name: Run lints
        working-directory: client
        run: yarn lint

  Rust-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install v4l2
        run: sudo apt-get install libv4l-0 libv4l-dev

      - name: Install JS dependencies
        working-directory: client
        run: yarn install --immutable --immutable-cache
      
      - name: Build static files
        working-directory: client
        run: yarn build

      - name: Run tests
        working-directory: pet-monitor-app
        run: cargo test

  Typescript-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: client
        run: yarn install --immutable --immutable-cache

      - name: Run tests
        working-directory: client
        run: yarn test