name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo sh ./scripts/build.sh

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo sh ./scripts/test.sh

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo sh ./scripts/lint.sh
