name: Build

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install v4l2
        run: sudo apt-get install libv4l-0 libv4l-dev

      - name: Build
        run: |
          cargo build -p pet-monitor-app
          cargo build -p v4l-streamer

  Typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: client
        run: yarn install --immutable --immutable-cache
      
      - name: Build
        working-directory: client
        run: yarn build
