name: Docker Image CI

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: CD

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        credentials: ${{ secrets.DOCKER_TOKEN }}
      run: sudo sh ./scripts/build.sh
